Develop
Shmakls/java-filmorate pull request #14
Opened 2022-07-02 07:52 UTC by Shmakls

Added functionals:
most popular, director, reviews, recommendations, remove, common films.

2022-07-03 16:34 UTC, eugene-lenkevich requested changes
Привет, Артур , спасибо за PR

В общем, команда постаралась, это видно, в целом все более чем солидно, предай им что все очень даже круто :)
Я постарался отметить самые важные моменты, которые можно улучшить, посмотри комментарии, пожалуйста :)

2022-07-03 16:34 UTC, eugene-lenkevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    /*public List<Film> topFilmsByLikes(@RequestParam(defaultValue = "10") Integer count) {
Закомментированный код не стоит оставлять, толку от него никакого :)

2022-07-03 16:34 UTC, eugene-lenkevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/DirectorsController.java
> +    public DirectorsController(FilmService filmService) {
Можно не задавать руками конструктор, можно добавить аннотацию lombok @RequiredArgsConstroctor

К тому же он у вас в проекте используется, гораздо лучше чтобы все было единообразно  :)

2022-07-03 16:34 UTC, eugene-lenkevich commented on src/main/java/ru/yandex/practicum/filmorate/model/Director.java
> +@RequiredArgsConstructor
Что то мне подсказывает, что конструктор создан не будет так как нет финальных полей, тут подойдет @AllArgsConstructor (и кстати такой конструктор создан руками, можно заменить =)

2022-07-03 16:34 UTC, eugene-lenkevich commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +                        .limit(count)
Получается что мы тут выгребаем все записи из базы данных (а если там сто миллиардов записей) и далее в стриме берем только часть. Лучше вынести это ограничение на слой БД, базы данных умеют с этим работать гораздо эффективнее :)

2022-07-03 16:34 UTC, eugene-lenkevich commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        DirectorValidator.isValid(director);
Валидатор стоит сделать бином и инжектить точно так же как и сторедж, иначе получается жесткая связь через статический метод, все преимущества спринга тут нивелируются :)

2022-07-03 16:34 UTC, eugene-lenkevich commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +            if (filmStorage.getFilmById(id) == null) {
Вот кажется, что будет красивее сделать метод filmStorage.isExists(id), который возвращает boolean :)

2022-07-03 16:34 UTC, eugene-lenkevich commented on src/main/java/ru/yandex/practicum/filmorate/storage/UserStorage/UserStorage.java
>      boolean isContains(Integer id);
Просто contains, так правильно с т.з. англ грамматики :)

2022-07-03 16:34 UTC, eugene-lenkevich commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/dao/FilmsDao.java
> +           film.setMpa(new MpaDao(jdbcTemplate).getMpaById(rowSet.getInt("rating_id")));
MpaDao стоит инжектить, это же бин, не стоит руками их создавать, мы так нивелируем все преимущества, которые нам превносит спринг :)

2022-07-03 16:34 UTC, eugene-lenkevich commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/dao/LikesListDao.java
> +        return new HashSet<>(jdbcTemplate.query(sql, (rs, rowNum) -> rs.getInt("film_id"), id));
Можно, кстати, сделать вот так
Collections.unmodifiableSet(...)

2022-07-03 16:34 UTC, eugene-lenkevich commented on src/main/java/ru/yandex/practicum/filmorate/validators/DirectorValidator.java
> +public class DirectorValidator {
Как писал выше, этот класс лучше сделать спринговым бином и инжектить куда надо :)

2022-07-03 16:34 UTC, eugene-lenkevich commented on src/main/java/ru/yandex/practicum/filmorate/validators/DirectorValidator.java
> +public class DirectorValidator {
Так же, пригодится в будущем понимание того, что статические методы не участвуют в наследовании так как не принадлежат конкретным объектам, а их классам, в общем, использовать статику - это как гвоздями прибивать :)

2022-07-04 07:51 UTC, Shmakls commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/dao/LikesListDao.java
> +        return new HashSet<>(jdbcTemplate.query(sql, (rs, rowNum) -> rs.getInt("film_id"), id));
Не совсем понял как реализовать. Метод query(...) возвращает List<Integer>, а unmodifiableSet(...) ждёт тип Set.

2022-07-04 17:49 UTC, eugene-lenkevich approved these changes
Все супер, спасибо!

Ребята, вы большие молодцы, все очень круто!

2022-07-04 18:21 UTC, merged