added friends likes rev 1
Shmakls/java-filmorate pull request #2
Opened 2022-05-26 20:21 UTC by Shmakls

2022-05-26 20:25 UTC, Shmakls commented
Евгений, здравствуйте!
При помощи напильника и какой-то матери мне удалось подогнать код под тесты PostMan.
Надеюсь всё будет работать. 
Я видел что у некоторых людей много комментариев в коде по их методам, видимо для более легкого понимания проверяющего. Скажите, нужно ли мне добавить такие же, чтобы Вам было проще ориентироваться в этом мракобесии?

2022-05-27 03:23 UTC, eugene-lenkevich requested changes
Привет, Артур, спасибо за PR

В целом все супер :)
Есть совсем небольшие замечания, посмотри комментарии ниже, пожалуйста

2022-05-27 03:23 UTC, eugene-lenkevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +    /* @ExceptionHandler
Закомментированный код не стоит оставлять, толку от него никакого :)

2022-05-27 03:23 UTC, eugene-lenkevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (count < 1) {
Это уже относится к бизнес логике, пусть проверка будет в сервисе, в контроллере стоит оставлять только то, что относится к обработке запросов :)

2022-05-27 03:23 UTC, eugene-lenkevich commented on src/main/java/ru/yandex/practicum/filmorate/exceptions/AlreadyExistException.java
> +public class AlreadyExistException extends RuntimeException {
extends Exception

Это штатная ситуация, ее стоит сделать проверяемым исключением. Непроверяемое - это ошибка в самом алгоритме работы, а это вполне себе штатная ситуация :)

2022-05-27 03:23 UTC, eugene-lenkevich commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            throw new IncorrectIdException("ИДИ НАХУЙ БЛЯТЬ С ТАКИМ ID");
Лучше избегать ненормативной лексики, вообще и всегда, один раз пошутил и забыл, а это потом может всплыть в самый неподходящий момент, например во время демо для заказчика :)
https://lurkmore.rip/Конина_блядская

2022-05-27 03:29 UTC, eugene-lenkevich commented
>  много комментариев в коде по их методам, видимо для более легкого понимания проверяющего

Привет =)
На самом деле комментариев не надо много. Код сам по себе должен, в идеале, быть написан так, чтобы не были нужны комментарии. В данном примере по коду все совершенно понятно что происходит. Плюсом, а что будет если код поменялся, а комментарий к нему поправить забыли.. ;)

https://habr.com/ru/post/645049/

2022-05-27 15:37 UTC, Shmakls commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            throw new IncorrectIdException("ИДИ НАХУЙ БЛЯТЬ С ТАКИМ ID");
Виноват, слегка подгорело что не было указано в условиях что ID не приходит с задачей, а генерируется программной, из-за чего под тесты Postman пришлось переделать кучу обычных тестов, так ещё и отрицательные ID начали пихать в PUT-запросы, не сказав ни слова про их обработку.

2022-05-27 15:43 UTC, Shmakls commented
Всё поправил, тесты Postman проходит.

2022-05-27 16:36 UTC, eugene-lenkevich approved these changes
Все супер, спасибо!

2022-05-27 16:40 UTC, merged