added work with H2 DB, added Genres and Mpa functional
Shmakls/java-filmorate pull request #3
Opened 2022-06-23 07:34 UTC by Shmakls

Евгений, здравствуйте!
Тесты в postman проходит, обычные тесты тоже, но только если запускать по одному. Я так и не понял как дропать всю базу после каждого теста, чтобы оптом сервис классы протестировать. 
В файле schema.sql есть закомментированная строка для дропа всех таблиц перед запуском. Я подгонял под тесты postmana. по-этому код гавно.

2022-06-23 08:51 UTC, Shmakls commented
Теперь я понял как дропать базу данных в тестах, все работает. Но чтобы это работало и проходило тут тесты, приходится дропать всю базу перед каждым запуском приложения (по мне это какая-то ерунда). Я не знаю что ещё тут нужно сделать.

2022-06-23 16:32 UTC, eugene-lenkevich commented
> Теперь я понял как дропать базу данных в тестах, все работает. Но чтобы это работало и проходило тут тесты, приходится дропать всю базу перед каждым запуском приложения (по мне это какая-то ерунда). Я не знаю что ещё тут нужно сделать.

Можно например инициализировать БД в @BeforeAll, а каждый метод сделать транзакционным, по завершении транзакция будет откатываться :)

https://habr.com/ru/post/433958/

2022-06-23 16:45 UTC, eugene-lenkevich requested changes
Привет, Артур, спасибо за PR
.
Нормальный код, не стоит обесценивать свой труд, понятно ж что он учебный :)
Оставил пару небольших комментариев))

2022-06-23 16:45 UTC, eugene-lenkevich commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/FilmDbStorage.java
> +        String sql = "SELECT * FROM FILMS WHERE film_id = ?";
Можно гораздо проще проверить существование записи ;)

select exists(SELECT id FROM FILMS WHERE film_id = ?)

2022-06-23 16:45 UTC, eugene-lenkevich commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/dao/LikesListDao.java
> +        String sql = "INSERT INTO LIKESLIST (film_id, user_id) VALUES (" + film.getId() + ", ?)";
(" + film.getId() + "

А зачем так, лучше использовать плейсходер, это более эффективно, планы таких запросов кэшируются, ну и в целом это безопасней так как данные экранируются в таком случае :)

2022-06-23 16:45 UTC, eugene-lenkevich commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/dao/MpaDao.java
> +        return allMpa.stream().filter(x -> x.getId() == id).findFirst().get();
А если не найдет запись? :)
Лучше сделать 
.findFirst().orElse(null)
.findFirst().orElseThrow(...)

2022-06-24 06:41 UTC, Shmakls commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/FilmDbStorage.java
> +        String sql = "SELECT * FROM FILMS WHERE film_id = ?";
Не совсем понял как это сделать. Код типа 
String sql  = "select exists(SELECT id FROM FILMS WHERE film_id = ?)";
return jdbcTemplate.update(sql, id) 
не работает, ругается что тип значения int, а тип boolean больше никто не возвращает.

2022-06-24 06:56 UTC, Shmakls commented
1-е замечание не поправил, потому-что не понял как :(.

2022-06-24 11:01 UTC, eugene-lenkevich approved these changes
Все супер, спасибо!

2022-06-24 11:06 UTC, eugene-lenkevich commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/FilmDbStorage.java
> +        String sql = "SELECT * FROM FILMS WHERE film_id = ?";
Ну, я не смогу просто глядя по коду подсказать, в принципе еще возможен вариант запроса
SELECT count(id) FROM FILMS WHERE film_id = ?

Но, в реальном проекте скорее всего будет использоваться другой фреймворк, скорее всего JPA или какой-нибудь myBatis, так что нет особого смысла сильно расковыривать голый jdbc, так что думаю не сильно критично если мы с этим моментом недоразбереся, главное отметить для себя что не обязательно что то из базы вытаскивать чтоыб просто проверить что запись существует :)

2022-06-25 07:10 UTC, merged